### ISSUE TITLE
Puppeteer old Headless deprecation warning

### ISSUE THREAD

**Issue by rdwz** [andwin/pagespeed-benchmark#17]
Running this: `pagespeed-benchmark https://www.example.com`

Displays this:
> Number of requests per url: 10
> Processing url: https://www.example.com

and for every request 
 
> Puppeteer old Headless deprecation warning:
>     In the near feature `headless: true` will default to the new Headless mode
>     for Chrome instead of the old Headless implementation. For more
>     information, please see https://developer.chrome.com/articles/new-headless/.
>     Consider opting in early by passing `headless: "new"` to `puppeteer.launch()`
>     If you encounter any bugs, please report them to https://github.com/puppeteer/puppeteer/issues/new/choose.

So the tool still works, it's just your terminal gets spoiled

**Comment by andwin** [comment]
Sounds good! I'm merging your pull request!
